# 请使用 CMake：见 CMakeLists.txt 与 tools/demo/run_all.*
BUILD_DEMO_DIR := ../../build/demo/make/interrupt_demo
TARGET := $(BUILD_DEMO_DIR)/interrupt_demo.elf
EXTRA_SRCS = interrupt_timer.c
include ../../tools/demo/qemu_example.mk
