#!/usr/bin/env python3
"""tools/amalgamate_ultra.py — generate bm-ultra-single.h from include/bm_ultra.h

Usage:
    python tools/amalgamate_ultra.py > bm-ultra-single.h
"""
import sys
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
INCLUDE_DIR = SCRIPT_DIR.parent / "include"


def read_header(path: Path) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def process_content(content: str, seen: set) -> str:
    """Expand local #include directives recursively."""
    lines = content.splitlines(keepends=True)
    out = []
    for line in lines:
        m = re.match(r'\s*#include\s+"([^"]+)"', line)
        if m:
            inc_name = m.group(1)
            inc_path = INCLUDE_DIR / inc_name
            if inc_path.exists() and inc_name not in seen:
                seen.add(inc_name)
                out.append(f"/* ---- begin {inc_name} ---- */\n")
                out.append(process_content(read_header(inc_path), seen))
                out.append(f"/* ---- end {inc_name} ---- */\n")
            else:
                # Skip duplicate or missing local includes;
                # keep system includes as-is.
                if not inc_path.exists():
                    out.append(line)
        else:
            out.append(line)
    return "".join(out)


def main():
    ultra_path = INCLUDE_DIR / "bm_ultra.h"
    if not ultra_path.exists():
        print(f"Error: {ultra_path} not found", file=sys.stderr)
        sys.exit(1)

    header = f"""/* bm-ultra-single.h — Amalgamated single-header distribution of bm-ultra
 * Generated by tools/amalgamate_ultra.py
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

"""
    seen = set()
    body = process_content(read_header(ultra_path), seen)
    print(header + body, end="")


if __name__ == "__main__":
    main()
