# Zeplod 集成预设：裁剪组件，避免逐项设置 BM_ENABLE_*

function(_zeplod_apply_profile PROFILE)
    if(PROFILE STREQUAL "minimal")
        set(_m OFF)
        set(_c OFF)
        set(_s OFF)
        set(_w OFF)
        set(_h OFF)
        set(_t OFF)
        set(_i OFF)
        set(_y OFF)
    elseif(PROFILE STREQUAL "event")
        set(_m ON)
        set(_c OFF)
        set(_s OFF)
        set(_w ON)
        set(_h OFF)
        set(_t OFF)
        set(_i OFF)
        set(_y OFF)
    elseif(PROFILE STREQUAL "servo")
        set(_m OFF)
        set(_c OFF)
        set(_s OFF)
        set(_w OFF)
        set(_h ON)
        set(_t ON)
        set(_i ON)
        set(_y OFF)
    elseif(PROFILE STREQUAL "full")
        set(_m ON)
        set(_c OFF)
        set(_s OFF)
        set(_w ON)
        set(_h ON)
        set(_t ON)
        set(_i ON)
        set(_y OFF)
    else()
        message(FATAL_ERROR "Unknown zeplod PROFILE: ${PROFILE}")
    endif()

    set(BM_ENABLE_MODULE ${_m} PARENT_SCOPE)
    set(BM_ENABLE_CHANNEL ${_c} PARENT_SCOPE)
    set(BM_ENABLE_SHELL ${_s} PARENT_SCOPE)
    set(BM_ENABLE_WDG ${_w} PARENT_SCOPE)
    set(BM_ENABLE_HRT ${_h} PARENT_SCOPE)
    set(BM_ENABLE_TICKER ${_t} PARENT_SCOPE)
    set(BM_ENABLE_EXEC ${_i} PARENT_SCOPE)
    set(BM_ENABLE_SYNC ${_y} PARENT_SCOPE)
endfunction()
